### ISSUE TITLE
Database shiny app

### ISSUE THREAD

**Issue by szymekdr** [elmacartney/Nongen_map_of_reviews#6]
To discuss @elmacartney @itchyshin

Database viewer is in R/shiny_database. To run the viewer set this folder as working directory, load in your console `library(shiny)` and run runApp('app') - or just run the `database_run.R` script.

- Multiple tables - if yes which ones? If yes
- [x] add code to load external files
--------
- Ad-hoc database == merge of several tables? If yes
- [x] add code to merge loaded tables
- [x] add drop-down lists to select relevant fields form tables (assuming only join interests us)
--------
- Do we want basic vis of selected vars (not sure if needed)? If yes - which, what type and then
- [x] add code rendering plots
--------
- [x] styling edits (smaller font, maybe other colours?)

**Comment by szymekdr** [comment]
@elmacartney the database is now working :)

**Comment by elmacartney** [comment]
Yay thank you!!
